### POST request to register a new user
POST http://localhost:3002/api/users/register
Content-Type: application/json

{
  "userName": "jmro4", 
  "name": "Juan Marcelo Rodriguez",
  "email": "newuser4@example.com",
  "password": "newPassword",
  "role": "doctor"
}

### POST request to login
POST http://localhost:3002/api/users/login
Content-Type: application/json

{
  "userName": "jmro2",
  "password": "newPassword"
}

### POST request to logout (if applicable)
POST http://localhost:3002/api/users/logout
Content-Type: application/json
Authorization: Bearer YOUR_BEARER_TOKEN

### GET request health check
GET http://localhost:3002/api/health

### GET request for all users
GET http://localhost:3002/api/users
Content-Type: application/json

### GET request for a specific user
GET http://localhost:3002/api/users/679e2f3fe9aa3966d22c8ce0
Content-Type: application/json

### PUT request to update a user
PUT http://localhost:3002/api/users/67a17b43c584e8c9f1a89789
Content-Type: application/json

{
  "userName": "jpcasa",
  "name": "Juan Pedro Casares",
  "email": "updatedemail3@example.com"
}

### DELETE request to delete a user
DELETE http://localhost:3002/api/users/67a17b43c584e8c9f1a89789
Content-Type: application/json
